# Generated by Django 5.1.6 on 2025-02-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flaggedaccount",
            name="limit",
            field=models.IntegerField(default="10000"),
            preserve_default=False,
        ),
    ]
