# Generated by Django 5.1.6 on 2025-02-07 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_flaggedaccount_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonFlaggedUpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upi_id", models.CharField(max_length=100)),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="non_flagged_upis",
                        to="app.flaggedaccount",
                    ),
                ),
            ],
        ),
    ]
