# Generated by Django 5.1.6 on 2025-02-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_nonflaggedupi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nonflaggedupi",
            name="account",
        ),
        migrations.AddField(
            model_name="nonflaggedupi",
            name="account_number",
            field=models.CharField(default="12345678956789", max_length=18),
            preserve_default=False,
        ),
    ]
